# Use an official node image as parent image
FROM node:16.14-alpine

#Set Container Time Zone
RUN apk add --no-cache tzdata
ENV TZ America/Chicago
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ./package*.json ./

# Install any needed packages specified in package.json
RUN npm install -g @angular/cli@13.1.3 && \
    npm install

#Copy the rest of the application
COPY . .

EXPOSE 4200 49153

CMD ["npm", "run", "start"]

